changed mail

diff --git a/sbrs b/sbrs
--- a/sbrs
+++ b/sbrs
@@ -1,26 +1,27 @@
 #!/bin/sh
 # See LICENSE file for copyright and license details.
 
-WEBSITE="https://christosmarg.xyz"
+WEBSITE="https://margiolis.net"
 AUTHOR="Christos Margiolis"
-BLOGDIR="blog"
+BLOGDIR="articles"
 DRAFTDIR=".drafts"
-BLOGINDEX="blog.html"
+BLOGINDEX="articles/index.html"
 INDEX="index.html"
 RSSFILE="rss.xml"
 TEMPLATE="template.html"
 test -z "${EDITOR}" && EDITOR="vim"
 
 main() {
-        test -f "${TEMPLATE}"     || err "${TEMPLATE}: missing file"
-        test -f "${BLOGINDEX}"    || err "${BLOGINDEX}: missing file"
-        test -f "${INDEX}"        || err "${INDEX}: missing file"
-        test -f "${RSSFILE}"      || err "${RSSFILE}: missing file"
+        test -f "${TEMPLATE}"   || err "${TEMPLATE}: missing file"
+        test -f "${BLOGINDEX}"  || err "${BLOGINDEX}: missing file"
+        test -f "${INDEX}"      || err "${INDEX}: missing file"
+        test -f "${RSSFILE}"    || err "${RSSFILE}: missing file"
 
         if ! test -d "${BLOGDIR}"; then
                 confirmact "Blog directory doesn't exist. Intialize it here (y/n)? " "y"
                 mkdir -pv "${BLOGDIR}"
         fi
+        # FIXME: ADD QUOTES INSIDE DATE ID
 
         case ${1} in
                 -n) newpost ;;
@@ -41,8 +42,8 @@ err() {
         echo "${0##*/}: $@" && exit
 }
 
-# We could be using `read -erp` but the -e and -p options don't work
-# or exist in all shells (e.g OpenBSD's `/bin/sh`).
+# Could just use `read -erp` but the -e and -p options don't work
+# or exist in all shells (e.g OpenBSD's ksh).
 xread() {
         printf "%s" "${1}" && read -r ${2}
 }
@@ -51,19 +52,20 @@ xread() {
 # implementations require a backup file with the -i option.
 # In this case, we make the backup files and immidiately delete
 # them afterwards because we probably don't need them.
-# We're using the extension `.psedbak` since we want to delete
-# only the files affected by `psed` and nothing else, and that's
+# We're using the extension `.sedibak` since we want to delete
+# only the files affected by `sedi` and nothing else, and that's
 # an easy way to make sure.
-psed() {
-        sed -i.psedbak "$@" && rm *.psedbak ${BLOGDIR}/*.psedbak 2>/dev/null
+sedi() {
+        sed -i.sedibak "$@" && rm *.sedibak ${BLOGDIR}/*.sedibak 2>/dev/null
 }
 
 confirmact() {
         xread "${1}" act && test "${act}" = "${2}" || exit 1
 }
 
+# TODO: sort by date
 list() {
-        find "${1}" -type f -name '*\.html' ! -name '*\.final*' 2> /dev/null |
+        find "${1}" -type f -name '*\.html' ! -name '*\.final*' 2>/dev/null |
         awk -F/ '{print $NF}'
 }
 
@@ -84,7 +86,7 @@ titlecheck() {
 }
 
 rmcontents() {
-        ls "${1}" | grep -x "${blogpost}\...*" | sed "s/^/${1}\//" | xargs rm
+        ls "${1}" | grep -x "${blogpost}\...*" | sed "s/^/${1}\//" | xargs -r rm
 }
 
 # -l option
@@ -107,7 +109,7 @@ listposts() {
         fi
 }
 
-# -n options
+# -n option
 newpost() {
         mkdir -p "${DRAFTDIR}"
         xread "Title: " title
@@ -136,7 +138,7 @@ titlechange() {
         # single instance of `and` in the file, and we don't want that. :-)
         # The < and > serve the same purpose, as `oldtitle` is
         # probably going to be inside an <a> or <title> tag.
-        psed "s/${blogpost}.html/${newtitlefmt}.html/g;s/>${oldtitle}</>${newtitle}</g" \
+        sedi "s/${blogpost}.html/${newtitlefmt}.html/g;s/>${oldtitle}</>${newtitle}</g" \
         "${BLOGDIR}/${blogpost}.html" "${INDEX}" "${BLOGINDEX}" "${RSSFILE}" &&
         mv "${BLOGDIR}/${blogpost}.html" "${BLOGDIR}/${newtitlefmt}.html" &&
         echo "Title changed successfully: ${oldtitle} -> ${newtitle}"
@@ -145,7 +147,7 @@ titlechange() {
 # -v option
 view() {
         cat "${DRAFTDIR}/${blogpost}.final.html" > "${DRAFTDIR}/${blogpost}.final-view.html"
-        psed "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.html" "${DRAFTDIR}/${blogpost}.final-view.html"
+        sedi "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.html" "${DRAFTDIR}/${blogpost}.final-view.html"
         ${BROWSER} "${DRAFTDIR}/${blogpost}.final-view.html"
 }
 
@@ -155,8 +157,8 @@ delete() {
 
         confirmact "Are you sure you want to delete \"${blogpost}\" (y/N)? " "y"
         if test "${dir}" = "${BLOGDIR}"; then
-                psed "/${blogpost}/d" "${INDEX}" "${BLOGINDEX}"
-                psed "/<\!--BEGIN ${blogpost}-->/,/<\!--END ${blogpost}-->/d" "${RSSFILE}"
+                sedi "/${blogpost}/d" "${INDEX}" "${BLOGINDEX}"
+                sedi "/<\!--BEGIN ${blogpost}-->/,/<\!--END ${blogpost}-->/d" "${RSSFILE}"
         fi
         rmcontents "${dir}" && echo "Removed ${blogpost}."
 }
@@ -168,8 +170,8 @@ publish() {
         title=$(titleget "${DRAFTDIR}/${blogpost}.final.html")
 
         # Make the final HTML file.
-        psed "s/^/\ \ \ \ \ \ \ \ /" "${DRAFTDIR}/${blogpost}.html"
-        psed "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.html" "${DRAFTDIR}/${blogpost}.final.html"
+        sedi "s/^/\ \ \ \ \ \ \ \ /" "${DRAFTDIR}/${blogpost}.html"
+        sedi "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.html" "${DRAFTDIR}/${blogpost}.final.html"
 
         # Convert HTML tags to XML format. We're also wrapping all <pre> tags
         # in a CDATA block so that RSS readers can render it properly.
@@ -186,26 +188,10 @@ publish() {
         # Prepare the RSS entry.
         rsscreate | expand -t8 > "${DRAFTDIR}/${blogpost}.final-rssentry"
 
-        # Update blog index to include the new post.
-        # In case there is not section for the current month, create that too.
-        dateid=$(date '+%b %Y' | sed 's/\ //' | tr '[:upper:]' '[:lower:]')
-
-        if test -z "$(grep "${dateid}" "${BLOGINDEX}")"; then
-                datename=$(date '+%B %Y')
-                psed "/<\!--SBRS-->/a\\
-\        <h2 id=\\"${dateid}\\">${datename}<\\/h2> \\
-\        <ul> \\
-\                <\\!--SBRS ${datename}--> \\
-\        <\\/ul> \\
-" "${BLOGINDEX}"
-        fi
-
-        # Using || because of `psed`.
-        psed "/<\!--SBRS $(date '+%B %Y')-->/r ${DRAFTDIR}/${blogpost}.final-htmlentry" \
-        "${BLOGINDEX}" || echo "Blogindex... done."
-
-        psed "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.final-htmlentry" "${INDEX}" || echo "Index... done"
-        psed "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.final-rssentry" "${RSSFILE}" || echo "RSS... done"
+        # Using || because of `sedi`.
+        sedi "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.final-htmlentry" "${BLOGINDEX}" || echo "blogindex: ok"
+        sedi "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.final-htmlentry" "${INDEX}" || echo "index: ok"
+        sedi "/<\!--SBRS-->/r ${DRAFTDIR}/${blogpost}.final-rssentry" "${RSSFILE}" || echo "rss: ok"
         
         # Remove the last blog entry from `index.html`.
         # Get only what's inside <!--SBRS--> and </ul>. Will not work on anything except
@@ -214,25 +200,25 @@ publish() {
 
         if test $(expr $(echo "${indexentries}" | wc -l)) -gt 7; then
                 lastentry=$(echo "${indexentries}" | tail -2 | head -1) &&
-                psed "s|${lastentry}||;" "${INDEX}"
+                sedi "s|${lastentry}||;" "${INDEX}"
         fi
         
-        rmcontents "${DRAFTDIR}" && echo "Cleaning up ${DRAFTDIR}... done"
+        rmcontents "${DRAFTDIR}" && echo "clean up ${DRAFTDIR}: ok"
         echo "Published ${blogpost}."
 }
 
 # -r option
 #revise() {
         #${EDITOR} "${BLOGDIR}/${blogpost}.html"
-        #psed "/<\!--BEGIN ${blogpost}-->/,/<\!--END ${blogpost}-->/d" "${RSSFILE}"
+        #sedi "/<\!--BEGIN ${blogpost}-->/,/<\!--END ${blogpost}-->/d" "${RSSFILE}"
 #}
 
 rsscreate() {
         printf "<!--BEGIN %s-->\n" "${blogpost}"
-        printf "<item>"
+        printf "<item>\n"
         printf "\t<title>%s</title>\n" "${title}"
         printf "\t<guid>%s</guid>\n" "${WEBSITE}/${BLOGDIR}/${blogpost}.html"
-        printf "\t<pubDate>%s</pubDate>\n" "$(date '+%a, %d %b %Y')" 
+        printf "\t<pubDate>%s</pubDate>\n" "$(date '+%a, %d %b %Y %T %z')" 
         printf "\t<description>\n"
         printf "%s\n" "$(cat "${DRAFTDIR}/${blogpost}.xml")"
         printf "\t</description>\n"
